import { DataTable } from "@/components/datatable-components/datatable"
import {Confirmation, Columns} from "@/app/confirmations/columns"

export default function Page() {

  const mockData: Confirmation[] = [
    {
      id: 1,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
    {
      id: 2,
      channel: "Agent",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      contact: "+0987654321",
      start: new Date("2024-01-15"),
      end: new Date("2024-02-20"),
      priority: "Medium",
      status: "Pending",
    },
    {
      id: 3,
      channel: "Referral",
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      contact: "+1122334455",
      start: new Date("2024-01-05"),
      end: new Date("2024-03-12"),
      priority: "Mid Priority",
      status: "Cancelled",
    },
    {
      id: 4,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 5,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 6,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 7,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 8,
      channel: "Agent",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      contact: "+0987654321",
      start: new Date("2024-01-15"),
      end: new Date("2024-02-20"),
      priority: "High Priority",
      status: "Pending",
    },
    {
      id: 9,
      channel: "Referral",
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      contact: "+1122334455",
      start: new Date("2024-01-05"),
      end: new Date("2024-03-12"),
      priority: "Low Priority",
      status: "Cancelled",
    },
    {
      id: 10,
      channel: "Online",
      name: "Gus Frank",
      email: "gus12345@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 11,
      channel: "Online",
      name: "Grigoris Champas",
      email: "grhak2000@gmail.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
    {
      id: 12,
      channel: "Online",
      name: "Stella Politaki",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 13,
      channel: "Online",
      name: "Katerina Champa",
      email: "katehk98@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
    {
      id: 1,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
    {
      id: 2,
      channel: "Agent",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      contact: "+0987654321",
      start: new Date("2024-01-15"),
      end: new Date("2024-02-20"),
      priority: "Mid Priority",
      status: "Pending",
    },
    {
      id: 3,
      channel: "Referral",
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      contact: "+1122334455",
      start: new Date("2024-01-05"),
      end: new Date("2024-03-12"),
      priority: "Mid Priority",
      status: "Cancelled",
    },
    {
      id: 4,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 5,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 6,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 7,
      channel: "Online",
      name: "John Doe",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 8,
      channel: "Agent",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      contact: "+0987654321",
      start: new Date("2024-01-15"),
      end: new Date("2024-02-20"),
      priority: "High Priority",
      status: "Pending",
    },
    {
      id: 9,
      channel: "Referral",
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      contact: "+1122334455",
      start: new Date("2024-01-05"),
      end: new Date("2024-03-12"),
      priority: "Low Priority",
      status: "Cancelled",
    },
    {
      id: 10,
      channel: "Online",
      name: "Gus Frank",
      email: "gus12345@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Mid Priority",
      status: "Confirmed",
    },
    {
      id: 11,
      channel: "Online",
      name: "Grigoris Champas",
      email: "grhak2000@gmail.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
    {
      id: 12,
      channel: "Online",
      name: "Stella Politaki",
      email: "john.doe@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "Low Priority",
      status: "Confirmed",
    },
    {
      id: 13,
      channel: "Online",
      name: "Katerina Champa",
      email: "katehk98@example.com",
      contact: "+1234567890",
      start: new Date("2024-01-01"),
      end: new Date("2024-01-10"),
      priority: "High Priority",
      status: "Confirmed",
    },
  ];

  return (
    <section className="mt-2 mx-4">
      {/* <hr className="shadow-sm"/> */}
      <div className="py-3">
        <DataTable columns={Columns} data={mockData} enablePagination={true} enableToolBar={true}></DataTable>
      </div>
    </section>
  )
}
